# Librairies and file loading

In [1]:
import pandas as pd
import numpy as np

## Quast metrics

In [2]:
file = "../Results/PAPER_BENCH.csv"

In [3]:
# Parsing tables within the CSV sheet
full = pd.read_csv(file, sep="\t", nrows=54, header=[0, 1], index_col=0, decimal=',')
ranks = pd.read_csv(file, sep="\t", skiprows=58, nrows=7, header=[0, 1], index_col=0, decimal=',')

main = pd.concat([full, ranks.loc[["Average Rank"]]])
main = main.swaplevel(0, 1, axis=1).sort_index(axis=1).replace({np.nan: -1})

main

                              3DDNA.FINAL                              \
                                  AG.DToL       AT.DtoL       BP.DtoL
# contigs (>= 0 bp)          1.695000e+03  4.580000e+02  5.046000e+03
# contigs (>= 1000 bp)       1.695000e+03  4.580000e+02  5.046000e+03
# contigs (>= 5000 bp)       1.623000e+03  4.420000e+02  4.922000e+03
# contigs (>= 10000 bp)      1.583000e+03  4.380000e+02  4.841000e+03
# contigs (>= 25000 bp)      1.383000e+03  4.050000e+02  4.321000e+03
# contigs (>= 50000 bp)      1.034000e+03  3.450000e+02  3.588000e+03
Total length (>= 0 bp)       1.398390e+09  1.390115e+08  2.850351e+09
Total length (>= 1000 bp)    1.398390e+09  1.390115e+08  2.850351e+09
Total length (>= 5000 bp)    1.398228e+09  1.389785e+08  2.850049e+09
Total length (>= 10000 bp)   1.397937e+09  1.389480e+08  2.849456e+09
Total length (>= 25000 bp)   1.394384e+09  1.383784e+08  2.839974e+09
Total length (>= 50000 bp)   1.382794e+09  1.365195e+08  2.813796e+09
# contigs                    1.647000e+03  4.470000e+02  4.963000e+03
Largest contig               7.668955e+07  3.928548e+07  1.579538e+07
Total length                 1.398316e+09  1.389975e+08  2.850211e+09
Reference length             1.398030e+09  1.388356e+08  2.850212e+09
GC (%)                       4.378000e+01  3.659000e+01  4.187000e+01
Reference GC (%)             4.378000e+01  3.659000e+01  4.187000e+01
N50                          5.235352e+06  6.920310e+05  2.124833e+06
NG50                         5.235352e+06  6.920310e+05  2.124833e+06
N90                          5.723140e+05  1.500000e+05  2.896760e+05
NG90                         5.723140e+05  1.500000e+05  2.896760e+05
auN                          1.010141e+07  1.154843e+07  2.831513e+06
auNG                         1.010347e+07  1.156190e+07  2.831512e+06
L50                          7.100000e+01  3.100000e+01  3.680000e+02
LG50                         7.100000e+01  3.100000e+01  3.680000e+02
L90                          3.940000e+02  2.090000e+02  1.728000e+03
LG90                         3.940000e+02  2.080000e+02  1.728000e+03
# misassemblies              7.360000e+02  3.500000e+02  7.280000e+02
# misassembled contigs       8.100000e+01  5.000000e+00  9.400000e+01
Misassembled contigs length  1.515574e+08  4.293243e+07  3.288740e+07
# local misassemblies        2.500000e+01  1.900000e+01  9.300000e+01
# scaffold gap ext. mis.     2.000000e+00  0.000000e+00  0.000000e+00
# scaffold gap loc. mis.     3.500000e+01  5.000000e+00  1.900000e+01
# possible TEs               0.000000e+00  0.000000e+00  2.000000e+00
# unaligned mis. contigs     0.000000e+00  0.000000e+00  0.000000e+00
Unaligned length             8.566350e+05  1.039818e+06  1.970484e+06
Genome fraction (%)          9.989700e+01  9.896700e+01  9.985900e+01
Duplication ratio            1.000000e+00  1.003000e+00  1.001000e+00
# N's per 100 kbp            2.832000e+01  1.320200e+02  1.368000e+01
# mismatches per 100 kbp     4.600000e-01  1.100000e+00  7.500000e-01
# indels per 100 kbp         3.000000e-02  2.100000e-01  5.000000e-02
Largest alignment            3.422791e+07  2.100000e+06  1.579538e+07
Total aligned length         1.397032e+09  1.377648e+08  2.847825e+09
NA50                         4.588998e+06  4.000000e+05  2.107820e+06
NGA50                        4.625000e+06  4.000000e+05  2.107820e+06
NA90                         4.250000e+05  7.500000e+04  2.644870e+05
NGA90                        4.250000e+05  7.500000e+04  2.644870e+05
auNA                         6.251393e+06  4.971274e+05  2.820609e+06
auNGA                        6.252672e+06  4.977072e+05  2.820607e+06
LA50                         8.300000e+01  1.010000e+02  3.690000e+02
LGA50                        8.200000e+01  1.010000e+02  3.690000e+02
LA90                         4.610000e+02  3.970000e+02  1.783000e+03
LGA90                        4.600000e+02  3.950000e+02  1.783000e+03
Average Rank                 4.000000e+00  4.000000e+00  3.750000e+00

                                                                       \
                                 Dro.DtoL    HG002.B10M      Vul.DToL
# contigs (>= 0 bp)          1.050000e+02  3.061000e+03  8.650000e+02
# contigs (>= 1000 bp)       1.050000e+02  3.061000e+03  8.650000e+02
# contigs (>= 5000 bp)       8.000000e+01  2.960000e+03  7.920000e+02
# contigs (>= 10000 bp)      7.000000e+01  2.891000e+03  7.500000e+02
# contigs (>= 25000 bp)      3.900000e+01  2.723000e+03  6.120000e+02
# contigs (>= 50000 bp)      2.000000e+01  2.214000e+03  3.880000e+02
Total length (>= 0 bp)       1.894136e+08  3.052669e+09  2.412481e+09
Total length (>= 1000 bp)    1.894136e+08  3.052669e+09  2.412481e+09
Total length (>= 5000 bp)    1.893595e+08  3.052441e+09  2.412323e+09
Total length (>= 10000 bp)   1.892873e+08  3.051921e+09  2.412019e+09
Total length (>= 25000 bp)   1.888113e+08  3.048939e+09  2.409550e+09
Total length (>= 50000 bp)   1.881664e+08  3.034748e+09  2.402309e+09
# contigs                    8.700000e+01  2.995000e+03  8.110000e+02
Largest contig               5.871518e+07  1.500475e+08  2.906531e+08
Total length                 1.893848e+08  3.052572e+09  2.412394e+09
Reference length             1.892655e+08  3.051513e+09  2.411727e+09
GC (%)                       3.747000e+01  4.082000e+01  4.134000e+01
Reference GC (%)             3.747000e+01  4.082000e+01  4.134000e+01
N50                          3.250693e+07  5.356462e+06  1.466656e+08
NG50                         3.250693e+07  5.356462e+06  1.466656e+08
N90                          2.680696e+07  6.260170e+05  1.013213e+08
NG90                         2.680696e+07  6.335380e+05  1.013213e+08
auN                          3.875998e+07  3.035957e+07  1.637422e+08
auNG                         3.878441e+07  3.037010e+07  1.637875e+08
L50                          3.000000e+00  6.800000e+01  6.000000e+00
LG50                         3.000000e+00  6.800000e+01  6.000000e+00
L90                          5.000000e+00  7.370000e+02  1.400000e+01
LG90                         5.000000e+00  7.350000e+02  1.400000e+01
# misassemblies              1.380000e+02  2.158000e+03  5.530000e+02
# misassembled contigs       8.000000e+00  9.500000e+01  4.000000e+01
Misassembled contigs length  1.858896e+08  1.326760e+09  2.351882e+09
# local misassemblies        1.400000e+01  7.000000e+00  1.260000e+02
# scaffold gap ext. mis.     0.000000e+00  1.000000e+00  5.000000e+00
# scaffold gap loc. mis.     3.000000e+02  1.500000e+01  1.642000e+03
# possible TEs               0.000000e+00  0.000000e+00  2.000000e+00
# unaligned mis. contigs     0.000000e+00  0.000000e+00  0.000000e+00
Unaligned length             1.317213e+06  2.524434e+06  3.522926e+06
Genome fraction (%)          9.926300e+01  9.990000e+01  9.974400e+01
Duplication ratio            1.000000e+00  1.000000e+00  1.001000e+00
# N's per 100 kbp            1.201300e+02  8.050000e+02  4.655000e+01
# mismatches per 100 kbp     4.500000e-01  2.300000e-01  1.420000e+00
# indels per 100 kbp         4.000000e-02  3.000000e-02  1.900000e-01
Largest alignment            3.163779e+07  8.237002e+07  6.279477e+07
Total aligned length         1.878396e+08  3.025493e+09  2.407724e+09
NA50                         1.431006e+07  2.550000e+06  1.606481e+07
NGA50                        1.431006e+07  2.550000e+06  1.606481e+07
NA90                         5.584000e+05  3.250000e+05  3.623018e+06
NGA90                        5.584000e+05  3.250000e+05  3.623018e+06
auNA                         1.626050e+07  6.269111e+06  2.027685e+07
auNGA                        1.627075e+07  6.271286e+06  2.028245e+07
LA50                         4.000000e+00  3.110000e+02  4.200000e+01
LGA50                        4.000000e+00  3.100000e+02  4.200000e+01
LA90                         2.900000e+01  1.500000e+03  1.510000e+02
LGA90                        2.900000e+01  1.497000e+03  1.510000e+02
Average Rank                 3.500000e+00  4.300000e+00  4.000000e+00

                                  AutoHic                              \
                                  AG.DToL       AT.DtoL       BP.DtoL
# contigs (>= 0 bp)          8.900000e+01  4.590000e+02  1.020000e+02
# contigs (>= 1000 bp)       8.700000e+01  4.590000e+02  1.000000e+02
# contigs (>= 5000 bp)       5.000000e+01  4.430000e+02  5.400000e+01
# contigs (>= 10000 bp)      2.800000e+01  4.390000e+02  3.000000e+01
# contigs (>= 25000 bp)      1.100000e+01  4.050000e+02  5.000000e+00
# contigs (>= 50000 bp)      7.000000e+00  3.450000e+02  3.000000e+00
Total length (>= 0 bp)       8.958641e+06  1.391955e+08  1.314002e+06
Total length (>= 1000 bp)    8.958639e+06  1.391955e+08  1.314000e+06
Total length (>= 5000 bp)    8.888639e+06  1.391625e+08  1.219000e+06
Total length (>= 10000 bp)   8.732639e+06  1.391320e+08  1.048000e+06
Total length (>= 25000 bp)   8.476639e+06  1.385435e+08  6.620650e+05
Total length (>= 50000 bp)   8.333639e+06  1.366831e+08  6.110650e+05
# contigs                    6.200000e+01  4.480000e+02  7.000000e+01
Largest contig               6.275000e+06  3.943211e+07  4.409550e+05
Total length                 8.931639e+06  1.391815e+08  1.276000e+06
Reference length             1.398030e+09  1.388356e+08  2.850212e+09
GC (%)                       4.515000e+01  3.659000e+01  4.915000e+01
Reference GC (%)             4.378000e+01  3.659000e+01  4.187000e+01
N50                          6.275000e+06  6.920310e+05  2.500000e+04
NG50                        -1.000000e+00  7.000000e+05 -1.000000e+00
N90                          8.074260e+05  1.500000e+05  8.000000e+03
NG90                        -1.000000e+00  1.500000e+05 -1.000000e+00
auN                          4.598443e+06  1.161693e+07  1.717306e+05
auNG                         2.937820e+04  1.164587e+07  7.690000e+01
L50                          1.000000e+00  3.100000e+01  5.000000e+00
LG50                        -1.000000e+00  3.000000e+01 -1.000000e+00
L90                          3.000000e+00  2.090000e+02  4.200000e+01
LG90                        -1.000000e+00  2.070000e+02 -1.000000e+00
# misassemblies              0.000000e+00  3.540000e+02  0.000000e+00
# misassembled contigs       0.000000e+00  5.000000e+00  0.000000e+00
Misassembled contigs length  0.000000e+00  4.309755e+07  0.000000e+00
# local misassemblies        0.000000e+00  2.300000e+01  0.000000e+00
# scaffold gap ext. mis.     0.000000e+00  0.000000e+00  0.000000e+00
# scaffold gap loc. mis.     0.000000e+00  4.000000e+00  0.000000e+00
# possible TEs               0.000000e+00  0.000000e+00  0.000000e+00
# unaligned mis. contigs     0.000000e+00  0.000000e+00  0.000000e+00
Unaligned length             0.000000e+00  1.039090e+06  0.000000e+00
Genome fraction (%)          5.840000e-01  9.895400e+01  1.900000e-02
Duplication ratio            1.000000e+00  1.003000e+00  1.000000e+00
# N's per 100 kbp            8.565060e+03  2.640400e+02  5.815047e+04
# mismatches per 100 kbp     0.000000e+00  1.530000e+00  0.000000e+00
# indels per 100 kbp         0.000000e+00  2.400000e-01  0.000000e+00
Largest alignment            6.275000e+06  2.100000e+06  4.409550e+05
Total aligned length         8.166639e+06  1.377662e+08  5.340000e+05
NA50                         6.275000e+06  4.000000e+05 -1.000000e+00
NGA50                       -1.000000e+00  4.000000e+05 -1.000000e+00
NA90                         8.074260e+05  7.500000e+04 -1.000000e+00
NGA90                       -1.000000e+00  7.500000e+04 -1.000000e+00
auNA                         4.595931e+06  4.961761e+05  1.543944e+05
auNGA                        2.936220e+04  4.974123e+05  6.910000e+01
LA50                         1.000000e+00  1.020000e+02 -1.000000e+00
LGA50                       -1.000000e+00  1.010000e+02 -1.000000e+00
LA90                         3.000000e+00  4.000000e+02 -1.000000e+00
LGA90                       -1.000000e+00  3.960000e+02 -1.000000e+00
Average Rank                 5.000000e+00  4.500000e+00  5.000000e+00

                                           ...    SPA-C.MR10                \
                                 Dro.DtoL  ...       BP.DtoL      Dro.DtoL
# contigs (>= 0 bp)          8.000000e+00  ...  2.457000e+03  1.230000e+02
# contigs (>= 1000 bp)       7.000000e+00  ...  2.457000e+03  1.230000e+02
# contigs (>= 5000 bp)       6.000000e+00  ...  2.454000e+03  1.210000e+02
# contigs (>= 10000 bp)      5.000000e+00  ...  2.440000e+03  1.200000e+02
# contigs (>= 25000 bp)      4.000000e+00  ...  2.275000e+03  8.900000e+01
# contigs (>= 50000 bp)      2.000000e+00  ...  1.900000e+03  7.500000e+01
Total length (>= 0 bp)       2.317482e+06  ...  2.848196e+09  1.891992e+08
Total length (>= 1000 bp)    2.316982e+06  ...  2.848196e+09  1.891992e+08
Total length (>= 5000 bp)    2.315982e+06  ...  2.848188e+09  1.891960e+08
Total length (>= 10000 bp)   2.306482e+06  ...  2.848077e+09  1.891864e+08
Total length (>= 25000 bp)   2.282883e+06  ...  2.845019e+09  1.886694e+08
Total length (>= 50000 bp)   2.205383e+06  ...  2.831464e+09  1.881970e+08
# contigs                    6.000000e+00  ...  2.456000e+03  1.210000e+02
Largest contig               2.086383e+06  ...  9.696410e+07  3.164443e+07
Total length                 2.315982e+06  ...  2.848195e+09  1.891960e+08
Reference length             1.892655e+08  ...  2.850212e+09  1.892655e+08
GC (%)                       3.674000e+01  ...  4.187000e+01  3.747000e+01
Reference GC (%)             3.747000e+01  ...  4.187000e+01  3.747000e+01
N50                          2.086383e+06  ...  3.171294e+07  2.595465e+07
NG50                        -1.000000e+00  ...  3.171294e+07  2.595465e+07
N90                          2.086383e+06  ...  4.451000e+05  1.017489e+06
NG90                        -1.000000e+00  ...  4.434350e+05  1.017489e+06
auN                          1.887282e+06  ...  3.681968e+07  2.106889e+07
auNG                         2.309410e+04  ...  3.679362e+07  2.106116e+07
L50                          1.000000e+00  ...  2.700000e+01  4.000000e+00
LG50                        -1.000000e+00  ...  2.700000e+01  4.000000e+00
L90                          1.000000e+00  ...  4.360000e+02  1.400000e+01
LG90                        -1.000000e+00  ...  4.400000e+02  1.400000e+01
# misassemblies              0.000000e+00  ...  4.680000e+02  3.200000e+01
# misassembled contigs       0.000000e+00  ...  3.410000e+02  1.900000e+01
Misassembled contigs length  0.000000e+00  ...  6.742302e+08  4.677289e+07
# local misassemblies        0.000000e+00  ...  5.800000e+01  2.000000e+00
# scaffold gap ext. mis.     0.000000e+00  ...  0.000000e+00  0.000000e+00
# scaffold gap loc. mis.     0.000000e+00  ...  0.000000e+00  0.000000e+00
# possible TEs               0.000000e+00  ...  0.000000e+00  0.000000e+00
# unaligned mis. contigs     0.000000e+00  ...  0.000000e+00  0.000000e+00
Unaligned length             0.000000e+00  ...  1.107373e+06  5.361400e+04
Genome fraction (%)          1.094000e+00  ...  9.963000e+01  9.993500e+01
Duplication ratio            1.000000e+00  ...  1.002000e+00  1.000000e+00
# N's per 100 kbp            1.062184e+04  ...  8.730000e+00  6.840000e+00
# mismatches per 100 kbp     0.000000e+00  ...  1.150000e+00  1.000000e-02
# indels per 100 kbp         0.000000e+00  ...  1.300000e-01  1.500000e-01
Largest alignment            2.066383e+06  ...  9.157766e+07  3.164433e+07
Total aligned length         2.069982e+06  ...  2.846189e+09  1.891261e+08
NA50                         2.066383e+06  ...  3.005340e+07  2.334469e+07
NGA50                       -1.000000e+00  ...  3.005340e+07  2.334469e+07
NA90                        -1.000000e+00  ...  3.537980e+05  8.144680e+05
NGA90                       -1.000000e+00  ...  3.500000e+05  8.144680e+05
auNA                         1.843690e+06  ...  3.488345e+07  2.023584e+07
auNGA                        2.256060e+04  ...  3.485876e+07  2.022841e+07
LA50                         1.000000e+00  ...  2.800000e+01  4.000000e+00
LGA50                       -1.000000e+00  ...  2.800000e+01  4.000000e+00
LA90                        -1.000000e+00  ...  5.550000e+02  1.800000e+01
LGA90                       -1.000000e+00  ...  5.600000e+02  1.800000e+01
Average Rank                 5.000000e+00  ...  1.750000e+00  1.500000e+00

                                                                 YaHS  \
                               HG002.B10M      Vul.DToL       AG.DToL
# contigs (>= 0 bp)          3.000000e+01  4.230000e+02  3.810000e+02
# contigs (>= 1000 bp)       3.000000e+01  4.230000e+02  3.810000e+02
# contigs (>= 5000 bp)       3.000000e+01  4.220000e+02  3.590000e+02
# contigs (>= 10000 bp)      3.000000e+01  4.190000e+02  3.540000e+02
# contigs (>= 25000 bp)      3.000000e+01  3.590000e+02  2.990000e+02
# contigs (>= 50000 bp)      3.000000e+01  3.070000e+02  1.970000e+02
Total length (>= 0 bp)       3.051516e+09  2.410700e+09  1.398032e+09
Total length (>= 1000 bp)    3.051516e+09  2.410700e+09  1.398032e+09
Total length (>= 5000 bp)    3.051516e+09  2.410698e+09  1.397994e+09
Total length (>= 10000 bp)   3.051516e+09  2.410677e+09  1.397960e+09
Total length (>= 25000 bp)   3.051516e+09  2.409505e+09  1.396974e+09
Total length (>= 50000 bp)   3.051516e+09  2.407646e+09  1.393263e+09
# contigs                    3.000000e+01  4.220000e+02  3.630000e+02
Largest contig               2.440222e+08  1.579476e+08  1.193360e+08
Total length                 3.051516e+09  2.410698e+09  1.398008e+09
Reference length             3.051513e+09  2.411727e+09  1.398030e+09
GC (%)                       4.082000e+01  4.134000e+01  4.378000e+01
Reference GC (%)             4.082000e+01  4.134000e+01  4.378000e+01
N50                          1.609551e+08  6.039280e+07  3.746360e+07
NG50                         1.609551e+08  6.039280e+07  3.746360e+07
N90                          7.890886e+07  1.340690e+07  2.010600e+07
NG90                         7.890886e+07  1.340690e+07  2.010600e+07
auN                          1.602129e+08  6.523184e+07  4.231312e+07
auNG                         1.602131e+08  6.520399e+07  4.231246e+07
L50                          8.000000e+00  1.400000e+01  1.400000e+01
LG50                         8.000000e+00  1.400000e+01  1.400000e+01
L90                          1.800000e+01  4.300000e+01  3.400000e+01
LG90                         1.800000e+01  4.300000e+01  3.400000e+01
# misassemblies              3.000000e+00  1.930000e+02  3.030000e+02
# misassembled contigs       3.000000e+00  9.000000e+01  8.600000e+01
Misassembled contigs length  2.168336e+08  1.684323e+09  8.122119e+08
# local misassemblies        0.000000e+00  4.300000e+01  9.700000e+01
# scaffold gap ext. mis.     0.000000e+00  0.000000e+00  0.000000e+00
# scaffold gap loc. mis.     5.000000e+00  0.000000e+00  8.300000e+01
# possible TEs               0.000000e+00  0.000000e+00  4.000000e+00
# unaligned mis. contigs     0.000000e+00  0.000000e+00  0.000000e+00
Unaligned length             0.000000e+00  1.113171e+06  1.220976e+06
Genome fraction (%)          9.999600e+01  9.962600e+01  9.983200e+01
Duplication ratio            1.000000e+00  1.002000e+00  1.001000e+00
# N's per 100 kbp            7.675100e+02  1.920000e+00  2.780000e+00
# mismatches per 100 kbp     0.000000e+00  6.200000e-01  6.500000e-01
# indels per 100 kbp         0.000000e+00  2.700000e-01  7.000000e-02
Largest alignment            2.440221e+08  1.203675e+08  5.509528e+07
Total aligned length         3.027985e+09  2.407837e+09  1.396739e+09
NA50                         1.543414e+08  3.580234e+07  2.468700e+07
NGA50                        1.543414e+08  3.580234e+07  2.468700e+07
NA90                         7.890876e+07  7.788968e+06  2.186000e+06
NGA90                        7.890876e+07  7.788968e+06  2.186000e+06
auNA                         1.536900e+08  3.997449e+07  2.567248e+07
auNGA                        1.536901e+08  3.995742e+07  2.567208e+07
LA50                         8.000000e+00  2.300000e+01  2.000000e+01

In [6]:
# Creating table for the paper
table = main.loc[["# misassemblies", "NGA50", "NGA90", "auNGA", "Average Rank"], ["YaHS", "Pin_hic", "3DDNA.FINAL", "AutoHic", "SPA-C.MR10"]].T
italic = lambda x: f"\\textit{{{x}}}"
table.rename(
    columns = {"Average Rank": r"Dataset rank$^{2}$", "# misassemblies": "\# misassemblies", "NGA50": r"NGA50$^{1}$", r"NGA90": r"NGA90$^{1}$", r"auNGA":r"auNGA$^{1}$"}, 
    index = {"Pin_hic": r"Pin\_hic","3DDNA.FINAL": "3D-DNA", "SPA-C.MR10": "SPA-C", "AG.DToL": italic("A. gentilis"), "AT.DtoL": italic("A. thaliana"), "BP.DtoL": italic("B. physalus"), "Dro.DtoL": italic("D. histrio"), "HG002.B10M": "HG002", "Vul.DToL": italic("V. vulpes")},
    inplace = True
)
for col in [r"NGA50$^{1}$", r"NGA90$^{1}$", r"auNGA$^{1}$"]:
    table[col] = table[col].astype(int) / 1000000
table["\# misassemblies"] = table["\# misassemblies"].astype(int)
table.index.names = ['Tool', 'Dataset']

## Computing global rank across datasets
avg_rank = table.groupby("Tool")[[r"Dataset rank$^{2}$"]].mean().rename(columns = {r"Dataset rank$^{2}$": "Global rank$^{3}$"})
table = table.reset_index(drop=False).merge(avg_rank, on='Tool').set_index(['Tool', 'Dataset']).apply(lambda x: x.apply(lambda y: np.nan if y < 0 else y) if np.issubdtype(x.dtype, np.number) else x)

table

                               \# misassemblies  NGA50$^{1}$  NGA90$^{1}$  \
Tool     Dataset
YaHS     \textit{A. gentilis}               303    24.686995     2.186000
         \textit{A. thaliana}                22    23.046581    11.191577
         \textit{B. physalus}               907    20.877564     0.404053
         \textit{D. histrio}                 61    28.847455     0.814464
         HG002                                7   133.581757    66.071906
         \textit{V. vulpes}                 277    55.405549    12.959486
Pin\_hic \textit{A. gentilis}                23    29.659553     3.001396
         \textit{A. thaliana}                10    13.127582     4.803106
         \textit{B. physalus}               119    15.412793     0.478000
         \textit{D. histrio}                 62     8.072125     0.706013
         HG002                                4   135.238171    50.222141
         \textit{V. vulpes}                 176    18.262914     4.231384
3D-DNA   \textit{A. gentilis}               736     4.625000     0.425000
         \textit{A. thaliana}               350     0.400000     0.075000
         \textit{B. physalus}               728     2.107820     0.264487
         \textit{D. histrio}                138    14.310062     0.558400
         HG002                             2158     2.550000     0.325000
         \textit{V. vulpes}                 553    16.064812     3.623018
AutoHic  \textit{A. gentilis}                 0          NaN          NaN
         \textit{A. thaliana}               354     0.400000     0.075000
         \textit{B. physalus}                 0          NaN          NaN
         \textit{D. histrio}                  0          NaN          NaN
         HG002                             2158     2.550000     0.325000
         \textit{V. vulpes}                   1          NaN          NaN
SPA-C    \textit{A. gentilis}               124    21.432086     2.612000
         \textit{A. thaliana}                 1    27.692325    15.776231
         \textit{B. physalus}               468    30.053400     0.350000
         \textit{D. histrio}                 32    23.344692     0.814468
         HG002                                3   154.341396    78.908764
         \textit{V. vulpes}                 193    35.802342     7.788968

                               auNGA$^{1}$  Dataset rank$^{2}$  \
Tool     Dataset
YaHS     \textit{A. gentilis}    25.672082                2.50
         \textit{A. thaliana}    23.766177                2.25
         \textit{B. physalus}    22.671188                2.75
         \textit{D. histrio}     21.782598                1.50
         HG002                  132.451758                2.50
         \textit{V. vulpes}      60.086159                1.50
Pin\_hic \textit{A. gentilis}    28.124638                1.00
         \textit{A. thaliana}    12.799478                2.75
         \textit{B. physalus}    17.956039                2.00
         \textit{D. histrio}     11.876755                3.75
         HG002                  131.440511                2.50
         \textit{V. vulpes}      21.437303                2.50
3D-DNA   \textit{A. gentilis}     6.252672                4.00
         \textit{A. thaliana}     0.497707                4.00
         \textit{B. physalus}     2.820607                3.75
         \textit{D. histrio}     16.270745                3.50
         HG002                    6.271285                4.30
         \textit{V. vulpes}      20.282453                4.00
AutoHic  \textit{A. gentilis}     0.029362                5.00
         \textit{A. thaliana}     0.497412                4.50
         \textit{B. physalus}     0.000069                5.00
         \textit{D. histrio}      0.022560                5.00
         HG002                    6.271749                4.00
         \textit{V. vulpes}       0.003398                5.00
SPA-C    \textit{A. gentilis}    22.519059                2.50
         \textit{A. thaliana}    25.192853                1.00
         \textit{B. physalus}    34.858760                1.75
         \textit{D. histrio}     20.228410                1.50
         HG002                  153.690107                1.00
         \textit{V. vulpes}      39.957418                2.00

                               Global rank$^{3}$
Tool     Dataset
YaHS     \textit{A. gentilis}           2.166667
         \textit{A. thaliana}           2.166667
         \textit{B. physalus}           2.166667
         \textit{D. histrio}            2.166667
         HG002                          2.166667
         \textit{V. vulpes}             2.166667
Pin\_hic \textit{A. gentilis}           2.416667
         \textit{A. thaliana}           2.416667
         \textit{B. physalus}           2.416667
         \textit{D. histrio}            2.416667
         HG002                          2.416667
         \textit{V. vulpes}             2.416667
3D-DNA   \textit{A. gentilis}           3.925000
         \textit{A. thaliana}           3.925000
         \textit{B. physalus}           3.925000
         \textit{D. histrio}            3.925000
         HG002                          3.925000
         \textit{V. vulpes}             3.925000
AutoHic  \textit{A. gentilis}           4.750000
         \textit{A. thaliana}           4.750000
         \textit{B. physalus}           4.750000
         \textit{D. histrio}            4.750000
         HG002                          4.750000
         \textit{V. vulpes}             4.750000
SPA-C    \textit{A. gentilis}           1.625000
         \textit{A. thaliana}           1.625000
         \textit{B. physalus}           1.625000
         \textit{D. histrio}            1.625000
         HG002                          1.625000
         \textit{V. vulpes}             1.625000

## Time metrics

In [7]:
tfile = "../Results/PAPER_TIME.csv"
time_df = pd.read_csv(tfile, sep="\t", header=0, index_col=None).set_index(['Step', 'Dataset'])
time_df

                   Juicer.time  Juicer.threads   HE.time  HE.threads  \
Step    Dataset
YaHS    HG002.B10M    31:13:17              16       NaN         NaN
        AT.DtoL       12:56:33              16       NaN         NaN
        Dro.DtoL      14:03:20              16       NaN         NaN
        AG.DToL       10:22:09              16       NaN         NaN
        Vul.DToL      28:10:54              16       NaN         NaN
        BP.DtoL       34:51:21              24       NaN         NaN
Pin_hic HG002.B10M    31:13:17              16       NaN         NaN
        AT.DtoL       12:56:33              16       NaN         NaN
        Dro.DtoL      14:03:20              16       NaN         NaN
        AG.DToL       10:22:09              16       NaN         NaN
        Vul.DToL      28:10:54              16       NaN         NaN
        BP.DtoL       34:51:21              24       NaN         NaN
3D-DNA  HG002.B10M    31:13:17              16       NaN         NaN
        AT.DtoL       12:56:33              16       NaN         NaN
        Dro.DtoL      14:03:20              16       NaN         NaN
        AG.DToL       10:22:09              16       NaN         NaN
        Vul.DToL      28:10:54              16       NaN         NaN
        BP.DtoL       34:51:21              24       NaN         NaN
AutoHic HG002.B10M    31:13:17              16       NaN         NaN
        AT.DtoL       12:56:33              16       NaN         NaN
        Dro.DtoL      14:03:20              16       NaN         NaN
        AG.DToL       10:22:09              16       NaN         NaN
        Vul.DToL      28:10:54              16       NaN         NaN
        BP.DtoL       34:51:21              24       NaN         NaN
SPA-C   HG002.B10M    31:13:17              16  10:13:18         4.0
        AT.DtoL       12:56:33              16  02:51:05         4.0
        Dro.DtoL      14:03:20              16  02:51:24         4.0
        AG.DToL       10:22:09              16  01:58:03         4.0
        Vul.DToL      28:10:54              16  13:06:06         4.0
        BP.DtoL       34:51:21              24  09:40:52         8.0

                    MND.time  MND.threads Tool.time  Tool.threads
Step    Dataset
YaHS    HG002.B10M       NaN          NaN  01:13:31           4.0
        AT.DtoL          NaN          NaN  25:50:00           4.0
        Dro.DtoL         NaN          NaN  00:30:03           4.0
        AG.DToL          NaN          NaN  00:20:39           4.0
        Vul.DToL         NaN          NaN  01:34:23          16.0
        BP.DtoL          NaN          NaN  01:36:34           4.0
Pin_hic HG002.B10M       NaN          NaN  03:34:11           4.0
        AT.DtoL          NaN          NaN  01:21:21           4.0
        Dro.DtoL         NaN          NaN  01:36:33           4.0
        AG.DToL          NaN          NaN  00:51:15           4.0
        Vul.DToL         NaN          NaN  04:19:11          16.0
        BP.DtoL          NaN          NaN  04:27:49           4.0
3D-DNA  HG002.B10M  02:21:05          8.0  62:58:43           4.0
        AT.DtoL     01:04:25          8.0  16:49:45           1.0
        Dro.DtoL    01:13:50          8.0  11:52:40           1.0
        AG.DToL     00:58:05          8.0  44:12:09           1.0
        Vul.DToL    05:11:11          8.0  51:50:28          16.0
        BP.DtoL     04:45:51          8.0  71:13:41           4.0
AutoHic HG002.B10M  02:21:05          8.0  41:21:47           4.0
        AT.DtoL     01:04:25          8.0  01:39:09           4.0
        Dro.DtoL    01:13:50          8.0  01:12:52           4.0
        AG.DToL     00:58:05          8.0  25:23:39           4.0
        Vul.DToL    05:11:11          8.0       NaN           NaN
        BP.DtoL     04:45:51          8.0       NaN           NaN
SPA-C   HG002.B10M       NaN          NaN  00:17:33           4.0
        AT.DtoL          NaN          NaN  00:02:09           4.0
        Dro.DtoL         NaN          NaN  00:07:03           4.0
        AG.DToL          NaN          NaN  00:20:20           4.0
        Vul.DToL         NaN          NaN  02:49:30           4.0
        BP.DtoL          NaN          NaN  07:37:12           4.0

In [8]:
import numpy as np

def time_to_seconds(time_str):
    if '-' in time_str:
        days, time_part = time_str.split('-', 1)
        days = int(days)
    else:
        days = 0
        time_part = time_str

    hh, mm, ss = map(int, time_part.split(':'))

    total_seconds = days * 86400 + hh * 3600 + mm * 60 + ss
    return total_seconds

def compute_all_time(row, df):
    row.dropna(inplace=True, axis=1)
    cols = row.columns
    steps = np.unique([col.split(".")[0] for col in cols])

    total_time = 0
    for step in steps:
        step_time = time_to_seconds(row.reset_index()[f"{step}.time"][0]) * int(row.reset_index()[f"{step}.threads"][0])
        total_time += step_time
        #print(total_time, step_time)

    if row.index[0][0] == "AutoHic":
        step_time = time_to_seconds(df.loc[("3D-DNA", row.index[0][1]), "Tool.time"])*df.loc[("3D-DNA", row.index[0][1]), "Tool.threads"]
        total_time += step_time
        print(total_time, step_time)
    
    return total_time

In [9]:
time_df["CPU time (s)"] = ([int(compute_all_time(time_df.iloc[[k]], time_df)) for k in range(len(time_df))])
time_df["CPU time (h)"] = (time_df["CPU time (s)"]//3600).astype(int)

time_df = time_df.reset_index().rename(
    columns = {"Step": "Tool"}, 
).set_index(['Tool', 'Dataset']).rename(
    index = {"Pin_hic": r"Pin\_hic", "AG.DToL": italic("A. gentilis"), "AT.DtoL": italic("A. thaliana"), "BP.DtoL": italic("B. physalus"), "Dro.DtoL": italic("D. histrio"), "HG002.B10M": "HG002", "Vul.DToL": italic("V. vulpes")}
)

time_df

3368592.0 906892.0
860789.0 60585.0
905288.0 42760.0
1149949.0 159129.0
4758680.0 2986048.0
4174436.0 1025684.0

                              Juicer.time  Juicer.threads   HE.time  \
Tool     Dataset
YaHS     HG002                   31:13:17              16       NaN
         \textit{A. thaliana}    12:56:33              16       NaN
         \textit{D. histrio}     14:03:20              16       NaN
         \textit{A. gentilis}    10:22:09              16       NaN
         \textit{V. vulpes}      28:10:54              16       NaN
         \textit{B. physalus}    34:51:21              24       NaN
Pin\_hic HG002                   31:13:17              16       NaN
         \textit{A. thaliana}    12:56:33              16       NaN
         \textit{D. histrio}     14:03:20              16       NaN
         \textit{A. gentilis}    10:22:09              16       NaN
         \textit{V. vulpes}      28:10:54              16       NaN
         \textit{B. physalus}    34:51:21              24       NaN
3D-DNA   HG002                   31:13:17              16       NaN
         \textit{A. thaliana}    12:56:33              16       NaN
         \textit{D. histrio}     14:03:20              16       NaN
         \textit{A. gentilis}    10:22:09              16       NaN
         \textit{V. vulpes}      28:10:54              16       NaN
         \textit{B. physalus}    34:51:21              24       NaN
AutoHic  HG002                   31:13:17              16       NaN
         \textit{A. thaliana}    12:56:33              16       NaN
         \textit{D. histrio}     14:03:20              16       NaN
         \textit{A. gentilis}    10:22:09              16       NaN
         \textit{V. vulpes}      28:10:54              16       NaN
         \textit{B. physalus}    34:51:21              24       NaN
SPA-C    HG002                   31:13:17              16  10:13:18
         \textit{A. thaliana}    12:56:33              16  02:51:05
         \textit{D. histrio}     14:03:20              16  02:51:24
         \textit{A. gentilis}    10:22:09              16  01:58:03
         \textit{V. vulpes}      28:10:54              16  13:06:06
         \textit{B. physalus}    34:51:21              24  09:40:52

                               HE.threads  MND.time  MND.threads Tool.time  \
Tool     Dataset
YaHS     HG002                        NaN       NaN          NaN  01:13:31
         \textit{A. thaliana}         NaN       NaN          NaN  25:50:00
         \textit{D. histrio}          NaN       NaN          NaN  00:30:03
         \textit{A. gentilis}         NaN       NaN          NaN  00:20:39
         \textit{V. vulpes}           NaN       NaN          NaN  01:34:23
         \textit{B. physalus}         NaN       NaN          NaN  01:36:34
Pin\_hic HG002                        NaN       NaN          NaN  03:34:11
         \textit{A. thaliana}         NaN       NaN          NaN  01:21:21
         \textit{D. histrio}          NaN       NaN          NaN  01:36:33
         \textit{A. gentilis}         NaN       NaN          NaN  00:51:15
         \textit{V. vulpes}           NaN       NaN          NaN  04:19:11
         \textit{B. physalus}         NaN       NaN          NaN  04:27:49
3D-DNA   HG002                        NaN  02:21:05          8.0  62:58:43
         \textit{A. thaliana}         NaN  01:04:25          8.0  16:49:45
         \textit{D. histrio}          NaN  01:13:50          8.0  11:52:40
         \textit{A. gentilis}         NaN  00:58:05          8.0  44:12:09
         \textit{V. vulpes}           NaN  05:11:11          8.0  51:50:28
         \textit{B. physalus}         NaN  04:45:51          8.0  71:13:41
AutoHic  HG002                        NaN  02:21:05          8.0  41:21:47
         \textit{A. thaliana}         NaN  01:04:25          8.0  01:39:09
         \textit{D. histrio}          NaN  01:13:50          8.0  01:12:52
         \textit{A. gentilis}         NaN  00:58:05          8.0  25:23:39
         \textit{V. vulpes}           NaN  05:11:11          8.0       NaN
         \textit{B. physalus}         NaN  04:45:51          8.0       NaN
SPA-C    HG002                        4.0       NaN          NaN  00:17:33
         \textit{A. thaliana}         4.0       NaN          NaN  00:02:09
         \textit{D. histrio}          4.0       NaN          NaN  00:07:03
         \textit{A. gentilis}         4.0       NaN          NaN  00:20:20
         \textit{V. vulpes}           4.0       NaN          NaN  02:49:30
         \textit{B. physalus}         8.0       NaN          NaN  07:37:12

                               Tool.threads  CPU time (s)  CPU time (h)
Tool     Dataset
YaHS     HG002                          4.0       1815996           504
         \textit{A. thaliana}           4.0       1117488           310
         \textit{D. histrio}            4.0        816812           226
         \textit{A. gentilis}           4.0        602220           167
         \textit{V. vulpes}            16.0       1713872           476
         \textit{B. physalus}           4.0       3034720           842
Pin\_hic HG002                          4.0       1849756           513
         \textit{A. thaliana}           4.0        765012           212
         \textit{D. histrio}            4.0        832772           231
         \textit{A. gentilis}           4.0        609564           169
         \textit{V. vulpes}            16.0       1872080           520
         \textit{B. physalus}           4.0       3075820           854
3D-DNA   HG002                          4.0       2772964           770
         \textit{A. thaliana}           1.0        836993           232
         \textit{D. histrio}            1.0        887800           246
         \textit{A. gentilis}           1.0        784273           217
         \textit{V. vulpes}            16.0       4758680          1321
         \textit{B. physalus}           4.0       4174436          1159
AutoHic  HG002                          4.0       3368592           935
         \textit{A. thaliana}           4.0        860789           239
         \textit{D. histrio}            4.0        905288           251
         \textit{A. gentilis}           4.0       1149949           319
         \textit{V. vulpes}             NaN       4758680          1321
         \textit{B. physalus}           NaN       4174436          1159
SPA-C    HG002                          4.0       1949756           541
         \textit{A. thaliana}           4.0        787064           218
         \textit{D. histrio}            4.0        852428           236
         \textit{A. gentilis}           4.0        630476           175
         \textit{V. vulpes}             4.0       1852608           514
         \textit{B. physalus}           4.0       3400088           944

# Merging

In [10]:
PTab = pd.concat([table, time_df[["CPU time (h)"]]], axis=1).iloc[:,[0, 1, 2, 3, 6, 4, 5]]
PTab

                               \# misassemblies  NGA50$^{1}$  NGA90$^{1}$  \
Tool     Dataset
YaHS     \textit{A. gentilis}               303    24.686995     2.186000
         \textit{A. thaliana}                22    23.046581    11.191577
         \textit{B. physalus}               907    20.877564     0.404053
         \textit{D. histrio}                 61    28.847455     0.814464
         HG002                                7   133.581757    66.071906
         \textit{V. vulpes}                 277    55.405549    12.959486
Pin\_hic \textit{A. gentilis}                23    29.659553     3.001396
         \textit{A. thaliana}                10    13.127582     4.803106
         \textit{B. physalus}               119    15.412793     0.478000
         \textit{D. histrio}                 62     8.072125     0.706013
         HG002                                4   135.238171    50.222141
         \textit{V. vulpes}                 176    18.262914     4.231384
3D-DNA   \textit{A. gentilis}               736     4.625000     0.425000
         \textit{A. thaliana}               350     0.400000     0.075000
         \textit{B. physalus}               728     2.107820     0.264487
         \textit{D. histrio}                138    14.310062     0.558400
         HG002                             2158     2.550000     0.325000
         \textit{V. vulpes}                 553    16.064812     3.623018
AutoHic  \textit{A. gentilis}                 0          NaN          NaN
         \textit{A. thaliana}               354     0.400000     0.075000
         \textit{B. physalus}                 0          NaN          NaN
         \textit{D. histrio}                  0          NaN          NaN
         HG002                             2158     2.550000     0.325000
         \textit{V. vulpes}                   1          NaN          NaN
SPA-C    \textit{A. gentilis}               124    21.432086     2.612000
         \textit{A. thaliana}                 1    27.692325    15.776231
         \textit{B. physalus}               468    30.053400     0.350000
         \textit{D. histrio}                 32    23.344692     0.814468
         HG002                                3   154.341396    78.908764
         \textit{V. vulpes}                 193    35.802342     7.788968

                               auNGA$^{1}$  CPU time (h)  Dataset rank$^{2}$  \
Tool     Dataset
YaHS     \textit{A. gentilis}    25.672082           167                2.50
         \textit{A. thaliana}    23.766177           310                2.25
         \textit{B. physalus}    22.671188           842                2.75
         \textit{D. histrio}     21.782598           226                1.50
         HG002                  132.451758           504                2.50
         \textit{V. vulpes}      60.086159           476                1.50
Pin\_hic \textit{A. gentilis}    28.124638           169                1.00
         \textit{A. thaliana}    12.799478           212                2.75
         \textit{B. physalus}    17.956039           854                2.00
         \textit{D. histrio}     11.876755           231                3.75
         HG002                  131.440511           513                2.50
         \textit{V. vulpes}      21.437303           520                2.50
3D-DNA   \textit{A. gentilis}     6.252672           217                4.00
         \textit{A. thaliana}     0.497707           232                4.00
         \textit{B. physalus}     2.820607          1159                3.75
         \textit{D. histrio}     16.270745           246                3.50
         HG002                    6.271285           770                4.30
         \textit{V. vulpes}      20.282453          1321                4.00
AutoHic  \textit{A. gentilis}     0.029362           319                5.00
         \textit{A. thaliana}     0.497412           239                4.50
         \textit{B. physalus}     0.000069          1159                5.00
         \textit{D. histrio}      0.022560           251                5.00
         HG002                    6.271749           935                4.00
         \textit{V. vulpes}       0.003398          1321                5.00
SPA-C    \textit{A. gentilis}    22.519059           175                2.50
         \textit{A. thaliana}    25.192853           218                1.00
         \textit{B. physalus}    34.858760           944                1.75
         \textit{D. histrio}     20.228410           236                1.50
         HG002                  153.690107           541                1.00
         \textit{V. vulpes}      39.957418           514                2.00

                               Global rank$^{3}$
Tool     Dataset
YaHS     \textit{A. gentilis}           2.166667
         \textit{A. thaliana}           2.166667
         \textit{B. physalus}           2.166667
         \textit{D. histrio}            2.166667
         HG002                          2.166667
         \textit{V. vulpes}             2.166667
Pin\_hic \textit{A. gentilis}           2.416667
         \textit{A. thaliana}           2.416667
         \textit{B. physalus}           2.416667
         \textit{D. histrio}            2.416667
         HG002                          2.416667
         \textit{V. vulpes}             2.416667
3D-DNA   \textit{A. gentilis}           3.925000
         \textit{A. thaliana}           3.925000
         \textit{B. physalus}           3.925000
         \textit{D. histrio}            3.925000
         HG002                          3.925000
         \textit{V. vulpes}             3.925000
AutoHic  \textit{A. gentilis}           4.750000
         \textit{A. thaliana}           4.750000
         \textit{B. physalus}           4.750000
         \textit{D. histrio}            4.750000
         HG002                          4.750000
         \textit{V. vulpes}             4.750000
SPA-C    \textit{A. gentilis}           1.625000
         \textit{A. thaliana}           1.625000
         \textit{B. physalus}           1.625000
         \textit{D. histrio}            1.625000
         HG002                          1.625000
         \textit{V. vulpes}             1.625000

# Export

In [11]:
# Temp fix
!pip install --upgrade jinja2

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: jinja2 in /home/amergez/.local/lib/python3.11/site-packages (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2) (3.0.2)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [17]:
Lcode = PTab.to_latex(float_format="%.2f")
Finalcode="".join([
    "\\begin{table*}[t]\n\\caption{Metrics on several high-quality, manually curated genomes. NGA associated values and the number of misassemblies were computed using \textit{Quast}. For each genome, the average rank of each tool was computed using its rankings on metrics and reported in ``Dataset rank''. A global rank was also computed for each tool by averaging its rankings on all datasets.}\n\\tabcolsep=0pt%%\n",
    Lcode.replace(
        "tabular", "tabular*"
    ).replace(
        "{llrrrrrrr}", r"{\textwidth}{@{\extracolsep{\fill}}llccccccc@{\extracolsep{\fill}}}"
    ).replace(
        r"\multirow[t]", r"\multirow"
    ).replace(
        r"1.50", r"\textbf{1.50}"
    ).replace(
        r"1.00", r"\textbf{1.00}"
    ).replace(
        r"1.75", r"\textbf{1.75}"
    ).replace( # Global ranks
        r"2.17", r"\multirow{6}{*}{2.17}", 1
    ).replace(
        r" 2.17", r" "
    ).replace( # Global ranks
        r"2.42", r"\multirow{6}{*}{2.42}", 1
    ).replace(
        r" 2.42", r" "
    ).replace( # Global ranks
        r"3.93", r"\multirow{6}{*}{3.93}", 1
    ).replace(
        r" 3.93", r" "
    ).replace( # Global ranks
        r"4.75", r"\multirow{6}{*}{4.75}", 1
    ).replace(
        r" 4.75", r" "
    ).replace( # Global ranks
        r"1.62", r"\multirow{6}{*}{\textbf{1.62}}", 1
    ).replace(
        r" 1.62", r" "
    ).replace(
        "\\cline{1-9}\n\\bottomrule", r"\botrule"
    ).replace(
        r" &  & \#", r" & Dataset & \#"
    ).replace(
        "Tool & Dataset &  &  &  &  &  &  &  \\\\\n\\midrule", r"\midrule"
    ).replace(
        "NaN", r"N.A.$^{4}$"
    ),
    "\\begin{tablenotes}\n\\item[$^{1}$] Expressed in Mbp.\n\\item[$^{2}$] Average rank based on ranks on NGA50, NGA90, auNGA and number of misassemblies.\n",
    "\\item[$^{3}$] Tool's average rank across datasets.\n\\item[$^{4}$] For some genomes, AutoHic's output contained $\\leq 1\%$ of the reference total length and was rank last.\n\\end{tablenotes}\n\\label{table:benchmark}\n\\end{table*}"
])
print(Finalcode)

\begin{table*}[t]
\caption{Metrics on several high-quality, manually curated genomes. NGA associated values and the number of misassemblies were computed using 	extit{Quast}. For each genome, the average rank of each tool was computed using its rankings on metrics and reported in ``Dataset rank''. A global rank was also computed for each tool by averaging its rankings on all datasets.}
\tabcolsep=0pt%%
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}llccccccc@{\extracolsep{\fill}}}
\toprule
 & Dataset & \# misassemblies & NGA50$^{1}$ & NGA90$^{1}$ & auNGA$^{1}$ & CPU time (h) & Dataset rank$^{2}$ & Global rank$^{3}$ \\
\midrule
\multirow{6}{*}{YaHS} & \textit{A. gentilis} & 303 & 24.69 & 2.19 & 25.67 & 167 & 2.50 & \multirow{6}{*}{2.17} \\
 & \textit{A. thaliana} & 22 & 23.05 & 11.19 & 23.77 & 310 & 2.25 &  \\
 & \textit{B. physalus} & 907 & 20.88 & 0.40 & 22.67 & 842 & 2.75 &  \\
 & \textit{D. histrio} & 61 & 28.85 & 0.81 & 21.78 & 226 & \textbf{1.50} &  \\
 & HG002 & 7 & 133.58 & 66.07 & 132.45 & 504 & 2.50 &  \\
 & \textit{V. vulpes} & 277 & 55.41 & 12.96 & 60.09 & 476 & \textbf{1.50} &  \\
\cline{1-9}
\multirow{6}{*}{Pin\_hic} & \textit{A. gentilis} & 23 & 29.66 & 3.00 & 28.12 & 169 & \textbf{1.00} & \multirow{6}{*}{2.42} \\
 & \textit{A. thaliana} & 10 & 13.13 & 4.80 & 12.80 & 212 & 2.75 &  \\
 & \textit{B. physalus} & 119 & 15.41 & 0.48 & 17.96 & 854 & 2.00 &  \\
 & \textit{D. histrio} & 62 & 8.07 & 0.71 & 11.88 & 231 & 3.75 &  \\
 & HG002 & 4 & 135.24 & 50.22 & 131.44 & 513 & 2.50 &  \\
 & \textit{V. vulpes} & 176 & 18.26 & 4.23 & 21.44 & 520 & 2.50 &  \\
\cline{1-9}
\multirow{6}{*}{3D-DNA} & \textit{A. gentilis} & 736 & 4.62 & 0.42 & 6.25 & 217 & 4.00 & \multirow{6}{*}{3.93} \\
 & \textit{A. thaliana} & 350 & 0.40 & 0.07 & 0.50 & 232 & 4.00 &  \\
 & \textit{B. physalus} & 728 & 2.11 & 0.26 & 2.82 & 1159 & 3.75 &  \\
 & \textit{D. histrio} & 138 & 14.31 & 0.56 & 16.27 & 246 & 3.50 &  \\
 & HG002 & 2158 & 2.55 & 0.33 & 6.27 & 770 & 4.30 &  \\
 & \textit{V. vulpes} & 553 & 16.06 & 3.62 & 20.28 & 1321 & 4.00 &  \\
\cline{1-9}
\multirow{6}{*}{AutoHic} & \textit{A. gentilis} & 0 & N.A.$^{4}$ & N.A.$^{4}$ & 0.03 & 319 & 5.00 & \multirow{6}{*}{4.75} \\
 & \textit{A. thaliana} & 354 & 0.40 & 0.07 & 0.50 & 239 & 4.50 &  \\
 & \textit{B. physalus} & 0 & N.A.$^{4}$ & N.A.$^{4}$ & 0.00 & 1159 & 5.00 &  \\
 & \textit{D. histrio} & 0 & N.A.$^{4}$ & N.A.$^{4}$ & 0.02 & 251 & 5.00 &  \\
 & HG002 & 2158 & 2.55 & 0.33 & 6.27 & 935 & 4.00 &  \\
 & \textit{V. vulpes} & 1 & N.A.$^{4}$ & N.A.$^{4}$ & 0.00 & 1321 & 5.00 &  \\
\cline{1-9}
\multirow{6}{*}{SPA-C} & \textit{A. gentilis} & 124 & 21.43 & 2.61 & 22.52 & 175 & 2.50 & \multirow{6}{*}{\textbf{1.62}} \\
 & \textit{A. thaliana} & 1 & 27.69 & 15.78 & 25.19 & 218 & \textbf{1.00} &  \\
 & \textit{B. physalus} & 468 & 30.05 & 0.35 & 34.86 & 944 & \textbf{1.75} &  \\
 & \textit{D. histrio} & 32 & 23.34 & 0.81 & 20.23 & 236 & \textbf{1.50} &  \\
 & HG002 & 3 & 154.34 & 78.91 & 153.69 & 541 & \textbf{1.00} &  \\
 & \textit{V. vulpes} & 193 & 35.80 & 7.79 & 39.96 & 514 & 2.00 &  \\
\botrule
\end{tabular*}
\begin{tablenotes}
\item[$^{1}$] Expressed in Mbp.
\item[$^{2}$] Average rank based on ranks on NGA50, NGA90, auNGA and number of misassemblies.
\item[$^{3}$] Tool's average rank across datasets.
\item[$^{4}$] For some genomes, AutoHic's output contained $\leq 1\%$ of the reference total length and was rank last.
\end{tablenotes}
\label{table:benchmark}
\end{table*}