# MR vs no MR figure/table

In [1]:
import pandas as pd

file = "../Results/SPAPER_MR.csv"

df = pd.read_csv(file, sep="\t", header=[0, 1], index_col=0)
df

                              HG002.B10M                  AT.DtoL              \
Assembly                      SPA-C.MR10     SPA-C.5k  SPA-C.MR10    SPA-C.5k
# contigs (>= 0 bp)                   30           32          30          26
# contigs (>= 1000 bp)                30           32          30          26
# contigs (>= 5000 bp)                30           32          30          26
# contigs (>= 10000 bp)               30           32          30          26
# contigs (>= 25000 bp)               30           32          27          23
# contigs (>= 50000 bp)               30           32          19          16
Total length (>= 0 bp)        3051515994   3051516182   138830976   138830576
Total length (>= 1000 bp)     3051515994   3051516182   138830976   138830576
Total length (>= 5000 bp)     3051515994   3051516182   138830976   138830576
Total length (>= 10000 bp)    3051515994   3051516182   138830976   138830576
Total length (>= 25000 bp)    3051515994   3051516182   138777165   138776765
Total length (>= 50000 bp)    3051515994   3051516182   138457564   138499619
# contigs                             30           32          30          26
Largest contig                 244022167    244022167    33256823    33256823
Total length                  3051515994   3051516182   138830976   138830576
Reference length              3051512984   3051512984   138835578   138835578
GC (%)                             40.82        40.82       36.59       36.59
Reference GC (%)                   40.82        40.82       36.59       36.59
N50                            160955130    154341496    27692425    27692425
NG50                           160955130    154341496    27692425    27692425
N90                             78908864     78908864    15776331    19630912
NG90                            78908864     78908864    15776331    19630912
auN                          160212930.6  154132359.5  25201445.9  26875137.2
auNG                         160213088.6    154132521  25200610.6  26874168.9
L50                                    8            8           3           3
LG50                                   8            8           3           3
L90                                   18           19           5           5
LG90                                  18           19           5           5
# misassemblies                        3            1           1           5
# misassembled contigs                 3            1           1           3
Misassembled contigs length    216833605    109467073      338480     3013935
# local misassemblies                  0            0           0           1
# scaffold gap ext. mis.               0            0           0           0
# scaffold gap loc. mis.               5            5           0           0
# possible TEs                         0            0           0           0
# unaligned mis. contigs               0            0           0           0
# unaligned contigs           0 + 0 part   0 + 0 part  0 + 0 part  0 + 1 part
Unaligned length                       0            0           0       19214
Genome fraction (%)               99.996       99.996      99.631      99.496
Duplication ratio                      1            1       1.003       1.004
# N's per 100 kbp                 767.51       767.52        2.16        1.87
# mismatches per 100 kbp               0            0         0.1        0.18
# indels per 100 kbp                   0            0        0.24         0.3
Largest alignment              244022067    244022067    33256670    33256670
Total aligned length          3027985239   3027985228   138758319   138736029
NA50                           154341396    154341396    27692325    27692325
NGA50                          154341396    154341396    27692325    27692325
NA90                            78908764     78908764    15776231    19630463
NGA90                           78908764     78908764    15776231    19630463
auNA                         153689955.8  153689945.7  25193688.1  26845812.3
auNGA                        153690107.4  153690106.8    25192853  26844845.1
LA50                                   8            8           3           3
LGA50                                  8            8           3           3
LA90                                  19           19           5           5
LGA90                                 19           19           5           5

                               Dro.DtoL                  AG.DtoL               \
Assembly                     SPA-C.MR10    SPA-C.5k   SPA-C.MR10     SPA-C.5k
# contigs (>= 0 bp)                 123         127          524          571
# contigs (>= 1000 bp)              123         127          524          571
# contigs (>= 5000 bp)              121         125          518          565
# contigs (>= 10000 bp)             120         124          517          564
# contigs (>= 25000 bp)              89          93          455          503
# contigs (>= 50000 bp)              75          78          349          397
Total length (>= 0 bp)        189199200   189199607   1397571636   1397576335
Total length (>= 1000 bp)     189199200   189199607   1397571636   1397576335
Total length (>= 5000 bp)     189196000   189196407   1397558036   1397562735
Total length (>= 10000 bp)    189186385   189186792   1397552846   1397557545
Total length (>= 25000 bp)    188669360   188669767   1396403638   1396431088
Total length (>= 50000 bp)    188196981   188170500   1392572591   1392601526
# contigs                           121         125          520          567
Largest contig                 31644432    56621278     60160386     60242393
Total length                  189196000   189196407   1397565236   1397569935
Reference length              189265483   189265483   1398030142   1398030142
GC (%)                            37.47       37.47        43.78        43.78
Reference GC (%)                  37.47       37.47        43.78        43.78
N50                            25954653    21018467     21995402     16751182
NG50                           25954653    21018467     21995402     16751182
N90                             1017489     1017489      2953720      1855100
NG90                            1017489     1017489      2953720      1855100
auN                          21068893.7  27079727.7   24187604.2     19693791
auNG                         21061158.9  27069844.4   24179560.7   19687308.1
L50                                   4           3           21           26
LG50                                  4           3           21           26
L90                                  14          15           76          112
LG90                                 14          15           76          112
# misassemblies                      32          30          124          131
# misassembled contigs               19          21           81           86
Misassembled contigs length    46772892   104673979    259946562    296735820
# local misassemblies                 2           3           92          143
# scaffold gap ext. mis.              0           0            0            0
# scaffold gap loc. mis.              0           0            0            0
# possible TEs                        0           0            2            0
# unaligned mis. contigs              0           0            0            0
# unaligned contigs          0 + 4 part  0 + 4 part  0 + 19 part  0 + 18 part
Unaligned length                  53614       62354       176137       358259
Genome fraction (%)              99.935      99.932       99.838       99.813
Duplication ratio                     1           1        1.001        1.001
# N's per 100 kbp                  6.84        7.05         3.75         4.09
# mismatches per 100 kbp           0.01        0.01         0.47         0.71
# indels per 100 kbp               0.15        0.15         0.07         0.07
Largest alignment              31644332    29700767     55195283     55195283
Total aligned length          189126128   189121055   1396816339   1396741070
NA50                           23344692    21018367     21432086     16461995
NGA50                          23344692    21018367     21432086     16461995
NA90                             814468      694913      2612000      1605000
NGA90                            814468      694913      2612000      1605000
auNA                         20235839.2  17399217.6   22526550.8   18161600.6
auNGA                        20228410.2  17392867.4   22519059.7   18155622.2
LA50                                  4           4           23           27
LGA50                                 4           4           23           27
LA90                                 18          21           82          125
LGA90                                18          21           82          125

                                Vul.DtoL                   BP.DtoL  \
Assembly                      SPA-C.MR10     SPA-C.5k   SPA-C.MR10
# contigs (>= 0 bp)                  423          435         2457
# contigs (>= 1000 bp)               423          435         2457
# contigs (>= 5000 bp)               422          434         2454
# contigs (>= 10000 bp)              419          431         2440
# contigs (>= 25000 bp)              359          371         2275
# contigs (>= 50000 bp)              307          319         1900
Total length (>= 0 bp)        2410699653   2410700739   2848196041
Total length (>= 1000 bp)     2410699653   2410700739   2848196041
Total length (>= 5000 bp)     2410697553   2410698639   2848188234
Total length (>= 10000 bp)    2410676998   2410678084   2848076661
Total length (>= 25000 bp)    2409505137   2409506223   2845018961
Total length (>= 50000 bp)    2407645685   2407652168   2831464029
# contigs                            422          434         2456
Largest contig                 157947587    167163817     96964098
Total length                  2410697553   2410698639   2848194941
Reference length              2411727275   2411727275   2850212336
GC (%)                             41.34        41.34        41.87
Reference GC (%)                   41.34        41.34        41.87
N50                             60392802     52634229     31712936
NG50                            60392802     52634229     31712936
N90                             13406896     13406896       445100
NG90                            13406896     13406896       443435
auN                           65231840.5   64419170.5   36819682.3
auNG                          65203988.8   64391694.8   36793621.1
L50                                   14           15           27
LG50                                  14           15           27
L90                                   43           46          436
LG90                                  43           46          440
# misassemblies                      193          167          468
# misassembled contigs                90           90          341
Misassembled contigs length   1684323224   1651620205    674230247
# local misassemblies                 43           22           58
# scaffold gap ext. mis.               0            0            0
# scaffold gap loc. mis.               0            0            0
# possible TEs                         0            0            0
# unaligned mis. contigs               0            0            0
# unaligned contigs          0 + 30 part  0 + 29 part  0 + 35 part
Unaligned length                 1113171      1130736      1107373
Genome fraction (%)               99.626       99.711        99.63
Duplication ratio                  1.002        1.002        1.002
# N's per 100 kbp                   1.92         1.97         8.73
# mismatches per 100 kbp            0.62         0.35         1.15
# indels per 100 kbp                0.27          0.2         0.13
Largest alignment              120367537     78590833     91577661
Total aligned length          2407836806   2408119297   2846188786
NA50                            35802342     36307465     30053400
NGA50                           35802342     36307465     30053400
NA90                             7788968      6763008       353798
NGA90                            7788968      6763008       350000
auNA                          39974486.1   36337904.2   34883451.1
auNGA                         39957418.4   36322405.5   34858760.4
LA50                                  23           24           28
LGA50                                 23           24           28
LA90                                  72           75          555
LGA90                                 72           75          560


Assembly                        SPA-C.5k
# contigs (>= 0 bp)                 2513
# contigs (>= 1000 bp)              2513
# contigs (>= 5000 bp)              2510
# contigs (>= 10000 bp)             2496
# contigs (>= 25000 bp)             2338
# contigs (>= 50000 bp)             1958
Total length (>= 0 bp)        2848201508
Total length (>= 1000 bp)     2848201508
Total length (>= 5000 bp)     2848193701
Total length (>= 10000 bp)    2848082128
Total length (>= 25000 bp)    2845185049
Total length (>= 50000 bp)    2831524355
# contigs                           2512
Largest contig                  97159098
Total length                  2848200408
Reference length              2850212336
GC (%)                             41.87
Reference GC (%)                   41.87
N50                             21322496
NG50                            21322496
N90                               445994
NG90                              444481
auN                           28629745.2
auNG                          28609535.9
L50                                   37
LG50                                  37
L90                                  493
LG90                                 497
# misassemblies                      481
# misassembled contigs               355
Misassembled contigs length    613854810
# local misassemblies                118
# scaffold gap ext. mis.               0
# scaffold gap loc. mis.               0
# possible TEs                         4
# unaligned mis. contigs               0
# unaligned contigs          0 + 41 part
Unaligned length                 1056320
Genome fraction (%)               99.564
Duplication ratio                  1.003
# N's per 100 kbp                   8.92
# mismatches per 100 kbp            1.39
# indels per 100 kbp                0.14
Largest alignment               91609269
Total aligned length          2845523846
NA50                            20014584
NGA50                           20014584
NA90                              353002
NGA90                             350000
auNA                          27209660.2
auNGA                         27190453.3
LA50                                  39
LGA50                                 39
LA90                                 605
LGA90                                610

In [2]:
import numpy as np
datasets = [tup[0] for tup in df.columns.tolist()[::2]]
datasets

sdf = df.loc[["NGA50", "NGA90", "auNGA", "# misassemblies"]]
for column in sdf.columns:
    sdf[column] = sdf[column].astype(float)/1000000 # Convert to Mb
sdf.loc["# misassemblies"] = (sdf.loc["# misassemblies"]*1000000).astype(int)  
sdf

                 HG002.B10M                AT.DtoL              Dro.DtoL  \
Assembly         SPA-C.MR10    SPA-C.5k SPA-C.MR10   SPA-C.5k SPA-C.MR10
NGA50            154.341396  154.341396  27.692325  27.692325  23.344692
NGA90             78.908764   78.908764  15.776231  19.630463   0.814468
auNGA            153.690107  153.690107  25.192853  26.844845  20.228410
# misassemblies    3.000000    1.000000   1.000000   5.000000  32.000000

                               AG.DtoL                Vul.DtoL              \
Assembly          SPA-C.5k  SPA-C.MR10    SPA-C.5k  SPA-C.MR10    SPA-C.5k
NGA50            21.018367   21.432086   16.461995   35.802342   36.307465
NGA90             0.694913    2.612000    1.605000    7.788968    6.763008
auNGA            17.392867   22.519060   18.155622   39.957418   36.322406
# misassemblies  30.000000  124.000000  131.000000  193.000000  167.000000

                   BP.DtoL
Assembly        SPA-C.MR10    SPA-C.5k
NGA50             30.05340   20.014584
NGA90              0.35000    0.350000
auNGA             34.85876   27.190453
# misassemblies  468.00000  481.000000

In [3]:
for ds in datasets:
    sdf[(ds, "Difference")] = (( (sdf[(ds, "SPA-C.MR10")] - sdf[(ds, "SPA-C.5k")]) / sdf[(ds, "SPA-C.5k")] ) * 100).astype(str).apply(lambda val: f"{float(val):.2f}%")
    
metrics = ["SPA-C.MR10", "SPA-C.5k", "Difference"]
new_columns = pd.MultiIndex.from_product([datasets, metrics], names=["Dataset", None])
sdf = sdf.reindex(columns=new_columns).T.rename(index={"SPA-C.MR10": "SPA-C", "SPA-C.5k":"SPA-C@5k"})

italic = lambda x: f"\\textit{{{x}}}"
sdf.rename(
    index={
        "AG.DtoL": italic("A. gentilis"), 
        "AT.DtoL": italic("A. thaliana"), 
        "BP.DtoL": italic("B. physalus"), 
        "Dro.DtoL": italic("D. histrio"), 
        "HG002.B10M": "HG002", 
        "Vul.DtoL": italic("V. vulpes")},
    columns={"# misassemblies": "\# misassemblies", "NGA50": r"NGA50$^{1}$", r"NGA90": r"NGA90$^{1}$", r"auNGA":r"auNGA$^{1}$"},
    inplace=True
)

sdf

                                NGA50$^{1}$ NGA90$^{1}$ auNGA$^{1}$  \
Dataset
HG002                SPA-C       154.341396   78.908764  153.690107
                     SPA-C@5k    154.341396   78.908764  153.690107
                     Difference       0.00%       0.00%       0.00%
\textit{A. thaliana} SPA-C        27.692325   15.776231   25.192853
                     SPA-C@5k     27.692325   19.630463   26.844845
                     Difference       0.00%     -19.63%      -6.15%
\textit{D. histrio}  SPA-C        23.344692    0.814468    20.22841
                     SPA-C@5k     21.018367    0.694913   17.392867
                     Difference      11.07%      17.20%      16.30%
\textit{A. gentilis} SPA-C        21.432086       2.612    22.51906
                     SPA-C@5k     16.461995       1.605   18.155622
                     Difference      30.19%      62.74%      24.03%
\textit{V. vulpes}   SPA-C        35.802342    7.788968   39.957418
                     SPA-C@5k     36.307465    6.763008   36.322406
                     Difference      -1.39%      15.17%      10.01%
\textit{B. physalus} SPA-C          30.0534        0.35    34.85876
                     SPA-C@5k     20.014584        0.35   27.190453
                     Difference      50.16%       0.00%      28.20%

                                \# misassemblies
Dataset
HG002                SPA-C                   3.0
                     SPA-C@5k                1.0
                     Difference          200.00%
\textit{A. thaliana} SPA-C                   1.0
                     SPA-C@5k                5.0
                     Difference          -80.00%
\textit{D. histrio}  SPA-C                  32.0
                     SPA-C@5k               30.0
                     Difference            6.67%
\textit{A. gentilis} SPA-C                 124.0
                     SPA-C@5k              131.0
                     Difference           -5.34%
\textit{V. vulpes}   SPA-C                 193.0
                     SPA-C@5k              167.0
                     Difference           15.57%
\textit{B. physalus} SPA-C                 468.0
                     SPA-C@5k              481.0
                     Difference           -2.70%

In [4]:
# Temp fix
!pip install --upgrade jinja2

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: jinja2 in /home/amergez/.local/lib/python3.11/site-packages (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2) (3.0.2)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [5]:
Lcode = sdf.to_latex(float_format="%.2f")
Finalcode="".join([
    "\\begin{table*}[t]\n\\caption{Comparison of SPA-C overall performance, with and without multi-resolution. With multi-resolution, the model predicts linkage pseudo-probability for each bin resolution independently. Similar predictions are then averaged between resolutions. We compared a default SPA-C run which uses $5$ kb and $25$ kb bin resolution matrices with a run using $5$ kb only. The difference made by using several resolutions is reported in percentage for each dataset. We used high-quality, curated genomes from the Darwin Tree of Life project and the HG002v1.1 maternal haplotype.}\n\\tabcolsep=0pt%%\n",
    Lcode.replace(
        "tabular", "tabular*"
    ).replace(
        "{llllll}", r"{\textwidth}{@{\extracolsep{\fill}}llcccc@{\extracolsep{\fill}}}"
    ).replace(
        r"\multirow[t]", r"\multirow"
    ).replace(
        r" &  & NGA", r"Dataset &  & NGA"
    ).replace(
        "Dataset &  &  &  &  &  \\\\\n\\midrule", r"\midrule"
    ).replace(
        "\\cline{1-6}\n\\bottomrule", r"\botrule"
    ).replace(
        "%", "\%"
    ),
    "\\begin{tablenotes}%\n%\\item\n\\item[$^{1}$] Expressed in Mbp.\n\\end{tablenotes}\n",
    "\\label{stable:mr}\n\\end{table*}"
])

print(Finalcode)

\begin{table*}[t]
\caption{Comparison of SPA-C overall performance, with and without multi-resolution. With multi-resolution, the model predicts linkage pseudo-probability for each bin resolution independently. Similar predictions are then averaged between resolutions. We compared a default SPA-C run which uses $5$ kb and $25$ kb bin resolution matrices with a run using $5$ kb only. The difference made by using several resolutions is reported in percentage for each dataset. We used high-quality, curated genomes from the Darwin Tree of Life project and the HG002v1.1 maternal haplotype.}
\tabcolsep=0pt%%
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}llcccc@{\extracolsep{\fill}}}
\toprule
Dataset &  & NGA50$^{1}$ & NGA90$^{1}$ & auNGA$^{1}$ & \# misassemblies \\
\midrule
\multirow{3}{*}{HG002} & SPA-C & 154.34 & 78.91 & 153.69 & 3.00 \\
 & SPA-C@5k & 154.34 & 78.91 & 153.69 & 1.00 \\
 & Difference & 0.00\% & 0.00\% & 0.00\% & 200.00\% \\
\cline{1-6}
\multirow{3}{*}{\textit{A. thaliana}} & SPA-C & 27.69 & 15.78 & 25.19 & 1.00 \\
 & SPA-C@5k & 27.69 & 19.63 & 26.84 & 5.00 \\
 & Difference & 0.00\% & -19.63\% & -6.15\% & -80.00\% \\
\cline{1-6}
\multirow{3}{*}{\textit{D. histrio}} & SPA-C & 23.34 & 0.81 & 20.23 & 32.00 \\
 & SPA-C@5k & 21.02 & 0.69 & 17.39 & 30.00 \\
 & Difference & 11.07\% & 17.20\% & 16.30\% & 6.67\% \\
\cline{1-6}
\multirow{3}{*}{\textit{A. gentilis}} & SPA-C & 21.43 & 2.61 & 22.52 & 124.00 \\
 & SPA-C@5k & 16.46 & 1.60 & 18.16 & 131.00 \\
 & Difference & 30.19\% & 62.74\% & 24.03\% & -5.34\% \\
\cline{1-6}
\multirow{3}{*}{\textit{V. vulpes}} & SPA-C & 35.80 & 7.79 & 39.96 & 193.00 \\
 & SPA-C@5k & 36.31 & 6.76 & 36.32 & 167.00 \\
 & Difference & -1.39\% & 15.17\% & 10.01\% & 15.57\% \\
\cline{1-6}
\multirow{3}{*}{\textit{B. physalus}} & SPA-C & 30.05 & 0.35 & 34.86 & 468.00 \\
 & SPA-C@5k & 20.01 & 0.35 & 27.19 & 481.00 \\
 & Difference & 50.16\% & 0.00\% & 28.20\% & -2.70\% \\
\botrule
\end{tabular*}
\begin{tablenotes}%
%\item
\item[$^{1}$] Expressed in Mbp.
\end{tablenotes}
\label{stable:mr}
\end{table*}