# LD vs no LD figure/table

In [1]:
import pandas as pd

file = "../Results/SPAPER_LD.csv"

df = pd.read_csv(file, sep="\t", header=[0, 1], index_col=0)
df

                              HG002.B10M                     AT.DtoL  \
Assembly                      SPA-C.MR10 SPA-C.MR10.noLD  SPA-C.MR10
# contigs (>= 0 bp)                   30              36          30
# contigs (>= 1000 bp)                30              36          30
# contigs (>= 5000 bp)                30              36          30
# contigs (>= 10000 bp)               30              36          30
# contigs (>= 25000 bp)               30              36          27
# contigs (>= 50000 bp)               30              36          19
Total length (>= 0 bp)        3051515994      3051516596   138830976
Total length (>= 1000 bp)     3051515994      3051516596   138830976
Total length (>= 5000 bp)     3051515994      3051516596   138830976
Total length (>= 10000 bp)    3051515994      3051516596   138830976
Total length (>= 25000 bp)    3051515994      3051516596   138777165
Total length (>= 50000 bp)    3051515994      3051516596   138457564
# contigs                             30              36          30
Largest contig                 244022167       244022167    33256823
Total length                  3051515994      3051516596   138830976
Reference length              3051512984      3051512984   138835578
GC (%)                             40.82           40.82       36.59
Reference GC (%)                   40.82           40.82       36.59
N50                            160955130       154341496    27692425
NG50                           160955130       154341496    27692425
N90                             78908864        83770281    15776331
NG90                            78908864        83770281    15776331
auN                          160212930.6     155248769.0  25201445.9
auNG                         160213088.6     155248952.7  25200610.6
L50                                    8               8           3
LG50                                   8               8           3
L90                                   18              18           5
LG90                                  18              18           5
# misassemblies                        3               6           1
# misassembled contigs                 3               5           1
Misassembled contigs length    216833605       360013811      338480
# local misassemblies                  0               0           0
# scaffold gap ext. mis.               0               0           0
# scaffold gap loc. mis.               5               5           0
# possible TEs                         0               0           0
# unaligned mis. contigs               0               0           0
# unaligned contigs           0 + 0 part      0 + 0 part  0 + 0 part
Unaligned length                       0               0           0
Genome fraction (%)               99.996          99.983      99.631
Duplication ratio                  1.000           1.000       1.003
# N's per 100 kbp                 767.51          767.53        2.16
# mismatches per 100 kbp            0.00            0.00        0.10
# indels per 100 kbp                0.00            0.00        0.24
Largest alignment              244022067       244022067    33256670
Total aligned length          3027985239      3027566862   138758319
NA50                           154341396       143803228    27692325
NGA50                          154341396       143803228    27692325
NA90                            78908764        66071306    15776231
NGA90                           78908764        66071306    15776231
auNA                         153689955.8     146150184.0  25193688.1
auNGA                        153690107.4     146150357.0  25192853.0
LA50                                   8               9           3
LGA50                                  8               9           3
LA90                                  19              20           5
LGA90                                 19              20           5

                                               Dro.DtoL                  \
Assembly                    SPA-C.MR10.noLD  SPA-C.MR10 SPA-C.MR10.noLD
# contigs (>= 0 bp)                      56         123             134
# contigs (>= 1000 bp)                   56         123             134
# contigs (>= 5000 bp)                   56         121             132
# contigs (>= 10000 bp)                  56         120             131
# contigs (>= 25000 bp)                  52          89             100
# contigs (>= 50000 bp)                  44          75              86
Total length (>= 0 bp)            138568504   189199200       189200301
Total length (>= 1000 bp)         138568504   189199200       189200301
Total length (>= 5000 bp)         138568504   189196000       189197101
Total length (>= 10000 bp)        138568504   189186385       189187486
Total length (>= 25000 bp)        138494593   188669360       188670461
Total length (>= 50000 bp)        138174992   188196981       188198082
# contigs                                56         121             132
Largest contig                     16172443    31644432        31644432
Total length                      138568504   189196000       189197101
Reference length                  138835578   189265483       189265483
GC (%)                                36.58       37.47           37.47
Reference GC (%)                      36.59       37.47           37.47
N50                                14461139    25954653        25954653
NG50                               14461139    25954653        25954653
N90                                 2085100     1017489          863504
NG90                                2061260     1017489          863504
auN                              12270483.6  21068893.7      20925927.4
auNG                             12246879.3  21061158.9      20918366.8
L50                                       5           4               4
LG50                                      5           4               4
L90                                      11          14              16
LG90                                     12          14              16
# misassemblies                           6          32              36
# misassembled contigs                    6          19              23
Misassembled contigs length        10447511    46772892        47288440
# local misassemblies                     4           2               2
# scaffold gap ext. mis.                  0           0               0
# scaffold gap loc. mis.                  0           0               0
# possible TEs                            0           0               0
# unaligned mis. contigs                  0           0               0
# unaligned contigs              0 + 0 part  0 + 4 part      0 + 5 part
Unaligned length                          0       53614           61480
Genome fraction (%)                  99.438      99.935          99.929
Duplication ratio                     1.004       1.000           1.000
# N's per 100 kbp                      4.04        6.84            7.42
# mismatches per 100 kbp               0.23        0.01            0.06
# indels per 100 kbp                   0.26        0.15            0.16
Largest alignment                  16171994    31644332        31644332
Total aligned length              138561671   189126128       189118127
NA50                               14461039    23344692        23344692
NGA50                              14461039    23344692        23344692
NA90                                1925000      814468          549998
NGA90                               1925000      814468          549998
auNA                             12255075.2  20235839.2      20213750.4
auNGA                            12231500.5  20228410.2      20206447.1
LA50                                      5           4               4
LGA50                                     5           4               4
LA90                                     12          18              21
LGA90                                    12          18              21

                                 AG.DtoL                     Vul.DtoL  \
Assembly                      SPA-C.MR10 SPA-C.MR10.noLD   SPA-C.MR10
# contigs (>= 0 bp)                  524             695          423
# contigs (>= 1000 bp)               524             695          423
# contigs (>= 5000 bp)               518             689          422
# contigs (>= 10000 bp)              517             688          419
# contigs (>= 25000 bp)              455             626          359
# contigs (>= 50000 bp)              349             519          307
Total length (>= 0 bp)        1397571636      1396924746   2410699653
Total length (>= 1000 bp)     1397571636      1396924746   2410699653
Total length (>= 5000 bp)     1397558036      1396911146   2410697553
Total length (>= 10000 bp)    1397552846      1396905956   2410676998
Total length (>= 25000 bp)    1396403638      1395758520   2409505137
Total length (>= 50000 bp)    1392572591      1391909005   2407645685
# contigs                            520             691          422
Largest contig                  60160386        59985386    157947587
Total length                  1397565236      1396918346   2410697553
Reference length              1398030142      1398030142   2411727275
GC (%)                             43.78           43.77        41.34
Reference GC (%)                   43.78           43.78        41.34
N50                             21995402        21840340     60392802
NG50                            21995402        21840340     60392802
N90                              2953720         1260100     13406896
NG90                             2953720         1240100     13406896
auN                           24187604.2      22987709.9   65231840.5
auNG                          24179560.7      22969428.8   65203988.8
L50                                   21              22           14
LG50                                  21              22           14
L90                                   76              97           43
LG90                                  76              98           43
# misassemblies                      124             180          193
# misassembled contigs                81             118           90
Misassembled contigs length    259946562       271441733   1684323224
# local misassemblies                 92              32           43
# scaffold gap ext. mis.               0               0            0
# scaffold gap loc. mis.               0               0            0
# possible TEs                         2               0            0
# unaligned mis. contigs               0               0            0
# unaligned contigs          0 + 19 part     0 + 18 part  0 + 30 part
Unaligned length                  176137          327773      1113171
Genome fraction (%)               99.838          99.797       99.626
Duplication ratio                  1.001           1.001        1.002
# N's per 100 kbp                   3.75            4.98         1.92
# mismatches per 100 kbp            0.47            0.52         0.62
# indels per 100 kbp                0.07            0.06         0.27
Largest alignment               55195283        55195283    120367537
Total aligned length          1396816339      1396175303   2407836806
NA50                            21432086        21032780     35802342
NGA50                           21432086        21032780     35802342
NA90                             2612000          858000      7788968
NGA90                            2612000          846110      7788968
auNA                          22526550.8      21358573.6   39974486.1
auNGA                         22519059.7      21341588.0   39957418.4
LA50                                  23              24           23
LGA50                                 23              24           23
LA90                                  82             111           72
LGA90                                 82             112           72

                                                 BP.DtoL
Assembly                    SPA-C.MR10.noLD   SPA-C.MR10 SPA-C.MR10.noLD
# contigs (>= 0 bp)                     440         2457            2656
# contigs (>= 1000 bp)                  440         2457            2656
# contigs (>= 5000 bp)                  439         2454            2653
# contigs (>= 10000 bp)                 436         2440            2639
# contigs (>= 25000 bp)                 376         2275            2473
# contigs (>= 50000 bp)                 324         1900            2094
Total length (>= 0 bp)           2410496906   2848196041      2847087032
Total length (>= 1000 bp)        2410496906   2848196041      2847087032
Total length (>= 5000 bp)        2410494806   2848188234      2847079225
Total length (>= 10000 bp)       2410474251   2848076661      2846967652
Total length (>= 25000 bp)       2409302390   2845018961      2843887062
Total length (>= 50000 bp)       2407443137   2831464029      2830184806
# contigs                               439         2456            2655
Largest contig                    157947587     96964098        96964099
Total length                     2410494806   2848194941      2847085932
Reference length                 2411727275   2850212336      2850212336
GC (%)                                41.34        41.87           41.87
Reference GC (%)                      41.34        41.87           41.87
N50                                56738813     31712936        31181339
NG50                               56738813     31712936        31181339
N90                                13406896       445100          385395
NG90                               13406896       443435          383693
auN                              63766563.1   36819682.3      35143778.1
auNG                             63733976.4   36793621.1      35105228.8
L50                                      15           27              28
LG50                                     15           27              28
L90                                      44          436             535
LG90                                     44          440             542
# misassemblies                         187          468             487
# misassembled contigs                   93          341             350
Misassembled contigs length      1713060579    674230247       619487876
# local misassemblies                    46           58             134
# scaffold gap ext. mis.                  0            0               0
# scaffold gap loc. mis.                  0            0               0
# possible TEs                            0            0               0
# unaligned mis. contigs                  0            0               0
# unaligned contigs             0 + 30 part  0 + 35 part     0 + 36 part
Unaligned length                    1128022      1107373         1322374
Genome fraction (%)                  99.627       99.630          99.567
Duplication ratio                     1.002        1.002           1.003
# N's per 100 kbp                      2.00         8.73            9.43
# mismatches per 100 kbp               0.61         1.15            1.30
# indels per 100 kbp                   0.26         0.13            0.14
Largest alignment                  86536834     91577661        91577662
Total aligned length             2407628482   2846188786      2844900500
NA50                               34686539     30053400        26339771
NGA50                              34686539     30053400        26339771
NA90                                7649533       353798          312153
NGA90                               7649533       350000          310000
auNA                             36251821.2   34883451.1      33267939.7
auNGA                            36233295.4   34858760.4      33231448.0
LA50                                     25           28              30
LGA50                                    25           28              30
LA90                                     74          555             670
LGA90                                    74          560             679

In [2]:
import numpy as np
datasets = [tup[0] for tup in df.columns.tolist()[::2]]
datasets

sdf = df.loc[["NGA50", "NGA90", "auNGA", "# misassemblies"]]
for column in sdf.columns:
    sdf[column] = sdf[column].astype(float)/1000000 # Convert to Mb
sdf.loc["# misassemblies"] = (sdf.loc["# misassemblies"]*1000000).astype(int)  
sdf

                 HG002.B10M                    AT.DtoL                  \
Assembly         SPA-C.MR10 SPA-C.MR10.noLD SPA-C.MR10 SPA-C.MR10.noLD
NGA50            154.341396      143.803228  27.692325       14.461039
NGA90             78.908764       66.071306  15.776231        1.925000
auNGA            153.690107      146.150357  25.192853       12.231500
# misassemblies    3.000000        6.000000   1.000000        6.000000

                  Dro.DtoL                     AG.DtoL                  \
Assembly        SPA-C.MR10 SPA-C.MR10.noLD  SPA-C.MR10 SPA-C.MR10.noLD
NGA50            23.344692       23.344692   21.432086       21.032780
NGA90             0.814468        0.549998    2.612000        0.846110
auNGA            20.228410       20.206447   22.519060       21.341588
# misassemblies  32.000000       36.000000  124.000000      180.000000

                   Vul.DtoL                    BP.DtoL
Assembly         SPA-C.MR10 SPA-C.MR10.noLD SPA-C.MR10 SPA-C.MR10.noLD
NGA50             35.802342       34.686539   30.05340       26.339771
NGA90              7.788968        7.649533    0.35000        0.310000
auNGA             39.957418       36.233295   34.85876       33.231448
# misassemblies  193.000000      187.000000  468.00000      487.000000

In [3]:
for ds in datasets:
    sdf[(ds, "Difference")] = (( (sdf[(ds, "SPA-C.MR10")] - sdf[(ds, "SPA-C.MR10.noLD")]) / sdf[(ds, "SPA-C.MR10.noLD")] ) * 100).astype(str).apply(lambda val: f"{float(val):.2f}%")
    
metrics = ["SPA-C.MR10", "SPA-C.MR10.noLD", "Difference"]
new_columns = pd.MultiIndex.from_product([datasets, metrics], names=["Dataset", None])
sdf = sdf.reindex(columns=new_columns).T.rename(index={"SPA-C.MR10": "SPA-C", "SPA-C.MR10.noLD":"SPA-C without Longdust"})

italic = lambda x: f"\\textit{{{x}}}"
sdf.rename(
    index={
        "AG.DtoL": italic("A. gentilis"), 
        "AT.DtoL": italic("A. thaliana"), 
        "BP.DtoL": italic("B. physalus"), 
        "Dro.DtoL": italic("D. histrio"), 
        "HG002.B10M": "HG002", 
        "Vul.DtoL": italic("V. vulpes")},
    columns={"# misassemblies": "\# misassemblies", "NGA50": r"NGA50$^{1}$", r"NGA90": r"NGA90$^{1}$", r"auNGA":r"auNGA$^{1}$"},
    inplace=True
)

sdf

                                            NGA50$^{1}$ NGA90$^{1}$  \
Dataset
HG002                SPA-C                   154.341396   78.908764
                     SPA-C without Longdust  143.803228   66.071306
                     Difference                   7.33%      19.43%
\textit{A. thaliana} SPA-C                    27.692325   15.776231
                     SPA-C without Longdust   14.461039       1.925
                     Difference                  91.50%     719.54%
\textit{D. histrio}  SPA-C                    23.344692    0.814468
                     SPA-C without Longdust   23.344692    0.549998
                     Difference                   0.00%      48.09%
\textit{A. gentilis} SPA-C                    21.432086       2.612
                     SPA-C without Longdust    21.03278     0.84611
                     Difference                   1.90%     208.71%
\textit{V. vulpes}   SPA-C                    35.802342    7.788968
                     SPA-C without Longdust   34.686539    7.649533
                     Difference                   3.22%       1.82%
\textit{B. physalus} SPA-C                      30.0534        0.35
                     SPA-C without Longdust   26.339771        0.31
                     Difference                  14.10%      12.90%

                                            auNGA$^{1}$ \# misassemblies
Dataset
HG002                SPA-C                   153.690107              3.0
                     SPA-C without Longdust  146.150357              6.0
                     Difference                   5.16%          -50.00%
\textit{A. thaliana} SPA-C                    25.192853              1.0
                     SPA-C without Longdust     12.2315              6.0
                     Difference                 105.97%          -83.33%
\textit{D. histrio}  SPA-C                     20.22841             32.0
                     SPA-C without Longdust   20.206447             36.0
                     Difference                   0.11%          -11.11%
\textit{A. gentilis} SPA-C                     22.51906            124.0
                     SPA-C without Longdust   21.341588            180.0
                     Difference                   5.52%          -31.11%
\textit{V. vulpes}   SPA-C                    39.957418            193.0
                     SPA-C without Longdust   36.233295            187.0
                     Difference                  10.28%            3.21%
\textit{B. physalus} SPA-C                     34.85876            468.0
                     SPA-C without Longdust   33.231448            487.0
                     Difference                   4.90%           -3.90%

In [4]:
Lcode = sdf.to_latex(float_format="%.2f")
Finalcode="".join([
    "\\begin{table*}[t]\n\\caption{Comparison of SPA-C overall performance, with and without \textit{Longdust}. \textit{Longdust} is used to detect low complexity regions from the sequence and discard the model's prediction in such regions. The difference made by using \textit{Longdust} is reported in percentage for each dataset. We used high-quality, curated genomes from the Darwin Tree of Life project and the HG002v1.1 maternal haplotype.}\n\\tabcolsep=0pt%%\n",
    Lcode.replace(
        "tabular", "tabular*"
    ).replace(
        "{llllll}", r"{\textwidth}{@{\extracolsep{\fill}}llcccc@{\extracolsep{\fill}}}"
    ).replace(
        r"\multirow[t]", r"\multirow"
    ).replace(
        r" &  & NGA", r"Dataset &  & NGA"
    ).replace(
        "Dataset &  &  &  &  &  \\\\\n\\midrule", r"\midrule"
    ).replace(
        "\\cline{1-6}\n\\bottomrule", r"\botrule"
    ).replace(
        "%", "\%"
    ),
    "\\begin{tablenotes}%\n%\\item\n\\item[$^{1}$] Expressed in Mbp.\n\\end{tablenotes}\n",
    "\\label{stable:longdust}\n\\end{table*}"
])

print(Finalcode)

\begin{table*}[t]
\caption{Comparison of SPA-C overall performance, with and without 	extit{Longdust}. 	extit{Longdust} is used to detect low complexity regions from the sequence and discard the model's prediction in such regions. The difference made by using 	extit{Longdust} is reported in percentage for each dataset. We used high-quality, curated genomes from the Darwin Tree of Life project and the HG002v1.1 maternal haplotype.}
\tabcolsep=0pt%%
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}llcccc@{\extracolsep{\fill}}}
\toprule
Dataset &  & NGA50$^{1}$ & NGA90$^{1}$ & auNGA$^{1}$ & \# misassemblies \\
\midrule
\multirow{3}{*}{HG002} & SPA-C & 154.34 & 78.91 & 153.69 & 3.00 \\
 & SPA-C without Longdust & 143.80 & 66.07 & 146.15 & 6.00 \\
 & Difference & 7.33\% & 19.43\% & 5.16\% & -50.00\% \\
\cline{1-6}
\multirow{3}{*}{\textit{A. thaliana}} & SPA-C & 27.69 & 15.78 & 25.19 & 1.00 \\
 & SPA-C without Longdust & 14.46 & 1.93 & 12.23 & 6.00 \\
 & Difference & 91.50\% & 719.54\% & 105.97\% & -83.33\% \\
\cline{1-6}
\multirow{3}{*}{\textit{D. histrio}} & SPA-C & 23.34 & 0.81 & 20.23 & 32.00 \\
 & SPA-C without Longdust & 23.34 & 0.55 & 20.21 & 36.00 \\
 & Difference & 0.00\% & 48.09\% & 0.11\% & -11.11\% \\
\cline{1-6}
\multirow{3}{*}{\textit{A. gentilis}} & SPA-C & 21.43 & 2.61 & 22.52 & 124.00 \\
 & SPA-C without Longdust & 21.03 & 0.85 & 21.34 & 180.00 \\
 & Difference & 1.90\% & 208.71\% & 5.52\% & -31.11\% \\
\cline{1-6}
\multirow{3}{*}{\textit{V. vulpes}} & SPA-C & 35.80 & 7.79 & 39.96 & 193.00 \\
 & SPA-C without Longdust & 34.69 & 7.65 & 36.23 & 187.00 \\
 & Difference & 3.22\% & 1.82\% & 10.28\% & 3.21\% \\
\cline{1-6}
\multirow{3}{*}{\textit{B. physalus}} & SPA-C & 30.05 & 0.35 & 34.86 & 468.00 \\
 & SPA-C without Longdust & 26.34 & 0.31 & 33.23 & 487.00 \\
 & Difference & 14.10\% & 12.90\% & 4.90\% & -3.90\% \\
\botrule
\end{tabular*}
\begin{tablenotes}%
%\item
\item[$^{1}$] Expressed in Mbp.
\end{tablenotes}
\label{stable:longdust}
\end{table*}